// <auto-generated />
namespace IN.Natteravnene.dk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAssociationIDLinkSPonsors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAssociationIDLinkSPonsors));
        
        string IMigrationMetadata.Id
        {
            get { return "201512022141342_AddAssociationIDLinkSPonsors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
