//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR.Localication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultForening {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultForening() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IN.Natteravnene.dk.Localisation.DefaultForening", typeof(DefaultForening).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string NoteTextTime {
            get {
                return ResourceManager.GetString("NoteTextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Velkommen til Natteravnene&lt;/h2&gt;
        ///&lt;p&gt;&lt;strong&gt;Natteravnenes formål er at skabe lokal tryghed og livsglæde - især blandt børn og unge i det offentlige rum.&lt;/strong&gt;
        ///&lt;p&gt;##ForeningsNavn## er en frivillig social forening, der går ture i hold på tre m/k’er efter lokalt behov – middag, aften eller nat - i de karakteristiske gule jakker.&lt;/p&gt;
        ///&lt;p&gt;Gennem synlighed og tilbud om ansvarlig voksenkontakt, er vi med til at skabe tryghed og støtte børn og unge der måtte have behov. En af sideeffekterne ved denne indsat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PageContentAbout {
            get {
                return ResourceManager.GetString("PageContentAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omside.
        /// </summary>
        public static string PageContentAboutTitle {
            get {
                return ResourceManager.GetString("PageContentAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;##ForeningsNavn## relevant links&lt;/p&gt;.
        /// </summary>
        public static string PageContentLink {
            get {
                return ResourceManager.GetString("PageContentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link side.
        /// </summary>
        public static string PageContentLinkTitle {
            get {
                return ResourceManager.GetString("PageContentLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Er du journalist og har behov for svar på og viden om ##ForeningsNavn##, Natteravnene generelt og vores syn på de unge i nattelivet, er vi klar til at hjælpe.&lt;/p&gt;
        ///&lt;p&gt;Kontakt&lt;/p&gt;.
        /// </summary>
        public static string PageContentPress {
            get {
                return ResourceManager.GetString("PageContentPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presseside.
        /// </summary>
        public static string PageContentPressTitle {
            get {
                return ResourceManager.GetString("PageContentPressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;##ForeningsNavn## er en frivillig social - non profit - organisation som primært finansieres gennem private midler.&lt;/p&gt;
        ///&lt;p&gt;Derfor er det altafgørende, at både private, fonde og virksomheder vil støtte vores arbejde. Nedenfor er vi stolte for at kunne præsentere vores sponsorer&lt;/p&gt;.
        /// </summary>
        public static string PageContentSponsor {
            get {
                return ResourceManager.GetString("PageContentSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorside.
        /// </summary>
        public static string PageContentSponsorTitle {
            get {
                return ResourceManager.GetString("PageContentSponsorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;Husk:&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;&lt;i&gt;Kan du ikke gå alligevel&lt;/i&gt;, skal DU gøre alt for at finde en afløser. Det kan du gøre enten gennem de frivillige i samråd med holdlederen, eller ved evt. at finde en person som du har tillid til, og som godt kunne tænke sig en prøvetur. Du kan via Ravnetur.dk udsende både e-mail og SMS til Ravnene for at høre, om der er nogen der har mulighed for at tage din tur. Lykkes dette IKKE så giv holdlederen besked og turen må aflyses./p&gt;.
        /// </summary>
        public static string Scheduletext {
            get {
                return ResourceManager.GetString("Scheduletext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string SendTeamTextDays {
            get {
                return ResourceManager.GetString("SendTeamTextDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej ##Fornavn##, Du skal ud og gå Natteravn ##Turstart## med ##Ravne##. Du bedes give tilbagemelding til Holdlederen ved at svare på denne SMS..
        /// </summary>
        public static string TeamMessage {
            get {
                return ResourceManager.GetString("TeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej ##Fornavn##, Du skal ud og gå Natteravn ##Turstart## med ##Ravne##. Du er Holdleder og der er sendt en besked til de andre om turen fra dig, så du skulle få besked fra dem. Hvis ikke må du følge op på Ravnene..
        /// </summary>
        public static string TeamMessageTeamLeader {
            get {
                return ResourceManager.GetString("TeamMessageTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBFHVI.
        /// </summary>
        public static string TextServiceProviderPassword {
            get {
                return ResourceManager.GetString("TextServiceProviderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFSA.
        /// </summary>
        public static string TextServiceProviderUserName {
            get {
                return ResourceManager.GetString("TextServiceProviderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Natteravnene i &lt;b&gt;{0}&lt;/b&gt; er nu oprettet i Ravnetur.dk, og er klar til brug.&lt;/p&gt;
        ///&lt;fieldset  style=&quot;background: #ffe600;margin: 8px;padding: 5px 20px 5px 20px;border: 2px solid #6d6e71;border-radius: 8px;-webkit-border-radius: 8px;-moz-border-radius: 8px;&quot;&gt;
        ///&lt;legend&gt;Brugernavn og Kodeord&lt;/legend&gt;
        ///Brugernavn: {1}&lt;br /&gt;
        ///Kodeord: {2}
        ///&lt;p&gt;&lt;b&gt;Husk:&lt;/b&gt; at du altid på Ravnetur.dk kan få dit brugernavn og kodeord tilsendt per SMS eller E-mail, i boksen til højre på forsiden.&lt;/b&gt;&lt;/p&gt;&lt;/fieldset&gt;
        ///&lt;p&gt;For at du k [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Welcomeemail {
            get {
                return ResourceManager.GetString("Welcomeemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej {0},
        ///Så er Natteravnene i {1} oprettet på Ravnetur.dk, og er klar til brug. For at logge ind brug nedestående.
        ///---
        ///Brugernavn &quot;&quot;{2}&quot;&quot;
        ///Kodeord &quot;&quot;{3}&quot;&quot;
        ///---
        ///Der er også sendt en e-mail med flere informationer.
        ///God fornøjelse
        ///Ravnetur.dk.
        /// </summary>
        public static string WelcomeTxt {
            get {
                return ResourceManager.GetString("WelcomeTxt", resourceCulture);
            }
        }
    }
}
