//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR.Localication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IN.Natteravnene.dk.Localisation.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny note {0}.
        /// </summary>
        public static string AssociationNewNote {
            get {
                return ResourceManager.GetString("AssociationNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} har fået ny Senior Instruktør.
        /// </summary>
        public static string AssociationSeniorInstructorChanged {
            get {
                return ResourceManager.GetString("AssociationSeniorInstructorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} har ændret status til {1}.
        /// </summary>
        public static string AssociationStatusChanged {
            get {
                return ResourceManager.GetString("AssociationStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} har ændret indholdsside .
        /// </summary>
        public static string ContentEdited {
            get {
                return ResourceManager.GetString("ContentEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} har givet tilbagemelding til Folder {1} .
        /// </summary>
        public static string FolderFedbackCompleated {
            get {
                return ResourceManager.GetString("FolderFedbackCompleated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er blokeret for Natteravne Nyt da det ikke har været muligt at levere..
        /// </summary>
        public static string MailBlocked {
            get {
                return ResourceManager.GetString("MailBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er oprettet som ny ravn.
        /// </summary>
        public static string NewPerson {
            get {
                return ResourceManager.GetString("NewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} har taget en manglende tur.
        /// </summary>
        public static string TakeTeam {
            get {
                return ResourceManager.GetString("TakeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold ændret.
        /// </summary>
        public static string TeamChanged {
            get {
                return ResourceManager.GetString("TeamChanged", resourceCulture);
            }
        }
    }
}
