//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR.Localication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Local_Homepage.Localisation.DomainStrings", typeof(DomainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udmeldt.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato udmeldelse.
        /// </summary>
        public static string AbsentDate {
            get {
                return ResourceManager.GetString("AbsentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreningens e-mail.
        /// </summary>
        public static string AssociationEmail {
            get {
                return ResourceManager.GetString("AssociationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officielle e-mail til foreningen.
        /// </summary>
        public static string AssociationEmailPrompt {
            get {
                return ResourceManager.GetString("AssociationEmailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forenings navn.
        /// </summary>
        public static string AssociationName {
            get {
                return ResourceManager.GetString("AssociationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreningens navn.
        /// </summary>
        public static string AssociationNamePrompt {
            get {
                return ResourceManager.GetString("AssociationNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forenings Nummer.
        /// </summary>
        public static string AssociationNumber {
            get {
                return ResourceManager.GetString("AssociationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilknytte Senior Instruktør.
        /// </summary>
        public static string AssociationSeniorInstructor {
            get {
                return ResourceManager.GetString("AssociationSeniorInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AssociationStatus {
            get {
                return ResourceManager.GetString("AssociationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string AssociationStatusActive {
            get {
                return ResourceManager.GetString("AssociationStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedlagt.
        /// </summary>
        public static string AssociationStatusClosed {
            get {
                return ResourceManager.GetString("AssociationStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bero.
        /// </summary>
        public static string AssociationStatusDorment {
            get {
                return ResourceManager.GetString("AssociationStatusDorment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunduddannelse.
        /// </summary>
        public static string BasicTraining {
            get {
                return ResourceManager.GetString("BasicTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato grunduddannelse.
        /// </summary>
        public static string BasicTrainingDate {
            get {
                return ResourceManager.GetString("BasicTrainingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fødselsdag.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasserer.
        /// </summary>
        public static string BoardFunctionTypeAccountant {
            get {
                return ResourceManager.GetString("BoardFunctionTypeAccountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppleant.
        /// </summary>
        public static string BoardFunctionTypeAlternate {
            get {
                return ResourceManager.GetString("BoardFunctionTypeAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisor.
        /// </summary>
        public static string BoardFunctionTypeAuditor {
            get {
                return ResourceManager.GetString("BoardFunctionTypeAuditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisorsuppleant.
        /// </summary>
        public static string BoardFunctionTypeAuditorAlternate {
            get {
                return ResourceManager.GetString("BoardFunctionTypeAuditorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestyrelsesmedlem.
        /// </summary>
        public static string BoardFunctionTypeBoardMember {
            get {
                return ResourceManager.GetString("BoardFunctionTypeBoardMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formand.
        /// </summary>
        public static string BoardFunctionTypeChairman {
            get {
                return ResourceManager.GetString("BoardFunctionTypeChairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string BoardFunctionTypeNone {
            get {
                return ResourceManager.GetString("BoardFunctionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næstformand.
        /// </summary>
        public static string BoardFunctionTypeViceChairman {
            get {
                return ResourceManager.GetString("BoardFunctionTypeViceChairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indhold.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man kan ikke bruge &quot;boks/lås kode funktion&quot; hvis man ikke bruger &quot;Send Note SMS&quot;.
        /// </summary>
        public static string BrugKeyBoxNoNote {
            get {
                return ResourceManager.GetString("BrugKeyBoxNoNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursusdato.
        /// </summary>
        public static string Causedate {
            get {
                return ResourceManager.GetString("Causedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursusbeskrivelse.
        /// </summary>
        public static string CauseDescription {
            get {
                return ResourceManager.GetString("CauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursusnavn.
        /// </summary>
        public static string CauseName {
            get {
                return ResourceManager.GetString("CauseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfimer nyt koderord.
        /// </summary>
        public static string Confirmnewpassword {
            get {
                return ResourceManager.GetString("Confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt telefon.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evt. officielle nummer til foreningen.
        /// </summary>
        public static string ContactPhonePrompt {
            get {
                return ResourceManager.GetString("ContactPhonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indhold.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danmark.
        /// </summary>
        public static string CountryDK {
            get {
                return ResourceManager.GetString("CountryDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Færøerne.
        /// </summary>
        public static string CountryFO {
            get {
                return ResourceManager.GetString("CountryFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grønland.
        /// </summary>
        public static string CountryGL {
            get {
                return ResourceManager.GetString("CountryGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sverige.
        /// </summary>
        public static string CountrySE {
            get {
                return ResourceManager.GetString("CountrySE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprettet.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuværende forening.
        /// </summary>
        public static string CurrentAssociation {
            get {
                return ResourceManager.GetString("CurrentAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuværende kodeord.
        /// </summary>
        public static string Currentpassword {
            get {
                return ResourceManager.GetString("Currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVR-nr..
        /// </summary>
        public static string CVRnr {
            get {
                return ResourceManager.GetString("CVRnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forenings CVR-nr. www.cvr.dk.
        /// </summary>
        public static string CVRnrPrompt {
            get {
                return ResourceManager.GetString("CVRnrPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVR-nr. forkert format skal være 8-cifre.
        /// </summary>
        public static string CVRWrongformat {
            get {
                return ResourceManager.GetString("CVRWrongformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grænse i timer for Frivillig turændringer.
        /// </summary>
        public static string DeadlineHoursTeamChange {
            get {
                return ResourceManager.GetString("DeadlineHoursTeamChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlagt modtagelse.
        /// </summary>
        public static string DeliverAt {
            get {
                return ResourceManager.GetString("DeliverAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afleveret.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skjul.
        /// </summary>
        public static string Depublish {
            get {
                return ResourceManager.GetString("Depublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributions niveau.
        /// </summary>
        public static string DistributionLevel {
            get {
                return ResourceManager.GetString("DistributionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varighed.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Værdien {0} er ikke gyldig for feltet {1}.
        /// </summary>
        public static string Er_DisplayFormat {
            get {
                return ResourceManager.GetString("Er_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved læsning fra Foreningsdatabasen.
        /// </summary>
        public static string ErrorAssociationDBError {
            get {
                return ResourceManager.GetString("ErrorAssociationDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etableret.
        /// </summary>
        public static string Established {
            get {
                return ResourceManager.GetString("Established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitets type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternavn.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fil titel.
        /// </summary>
        public static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fil type.
        /// </summary>
        public static string FilType {
            get {
                return ResourceManager.GetString("FilType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slut.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornavn.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash SMS.
        /// </summary>
        public static string FlashSMS {
            get {
                return ResourceManager.GetString("FlashSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappenavn.
        /// </summary>
        public static string Foldername {
            get {
                return ResourceManager.GetString("Foldername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkiveret.
        /// </summary>
        public static string FolderStatusArchived {
            get {
                return ResourceManager.GetString("FolderStatusArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string FolderStatusInput {
            get {
                return ResourceManager.GetString("FolderStatusInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny.
        /// </summary>
        public static string FolderStatusNew {
            get {
                return ResourceManager.GetString("FolderStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiceret.
        /// </summary>
        public static string FolderStatusPubliceret {
            get {
                return ResourceManager.GetString("FolderStatusPubliceret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Føl-information.
        /// </summary>
        public static string FolInfo {
            get {
                return ResourceManager.GetString("FolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulde navn.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Køn.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mand.
        /// </summary>
        public static string GenderMan {
            get {
                return ResourceManager.GetString("GenderMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke defineret.
        /// </summary>
        public static string GenderNotDefined {
            get {
                return ResourceManager.GetString("GenderNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvinde.
        /// </summary>
        public static string GenderWoman {
            get {
                return ResourceManager.GetString("GenderWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestyrelsesform.
        /// </summary>
        public static string GovernanceType {
            get {
                return ResourceManager.GetString("GovernanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styregruppe.
        /// </summary>
        public static string GovernanceTypeSteeringgroup {
            get {
                return ResourceManager.GetString("GovernanceTypeSteeringgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditionel.
        /// </summary>
        public static string GovernanceTypeTraditionel {
            get {
                return ResourceManager.GetString("GovernanceTypeTraditionel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overskrift.
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID NR web.
        /// </summary>
        public static string IDWEB {
            get {
                return ResourceManager.GetString("IDWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorer distribution.
        /// </summary>
        public static string IgnorDistribution {
            get {
                return ResourceManager.GetString("IgnorDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internt.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekymring med forening.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boks/lås kode.
        /// </summary>
        public static string KeyBoxcode {
            get {
                return ResourceManager.GetString("KeyBoxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidst rettet.
        /// </summary>
        public static string Lastchanged {
            get {
                return ResourceManager.GetString("Lastchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidste kontakt LS.
        /// </summary>
        public static string LastContactHQ {
            get {
                return ResourceManager.GetString("LastContactHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalt.
        /// </summary>
        public static string LevelTypeGlobaly {
            get {
                return ResourceManager.GetString("LevelTypeGlobaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalt.
        /// </summary>
        public static string LevelTypeLocal {
            get {
                return ResourceManager.GetString("LevelTypeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalt.
        /// </summary>
        public static string LevelTypeNational {
            get {
                return ResourceManager.GetString("LevelTypeNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværk.
        /// </summary>
        public static string LevelTypeNetvork {
            get {
                return ResourceManager.GetString("LevelTypeNetvork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rækker i lister.
        /// </summary>
        public static string ListLines {
            get {
                return ResourceManager.GetString("ListLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string lng {
            get {
                return ResourceManager.GetString("lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokation.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv lokation.
        /// </summary>
        public static string LocationActive {
            get {
                return ResourceManager.GetString("LocationActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på lokation.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis på national kort.
        /// </summary>
        public static string LocationShowNationaMap {
            get {
                return ResourceManager.GetString("LocationShowNationaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husk mig?.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max tur i perioden.
        /// </summary>
        public static string MaxTeams {
            get {
                return ResourceManager.GetString("MaxTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødedato.
        /// </summary>
        public static string MeetingDate {
            get {
                return ResourceManager.GetString("MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besked.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestyrelsesmøde.
        /// </summary>
        public static string MinutesTypeBoardmeeting {
            get {
                return ResourceManager.GetString("MinutesTypeBoardmeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstraordinær generalforsamling.
        /// </summary>
        public static string MinutesTypeExtraordinaryGeneralMeeting {
            get {
                return ResourceManager.GetString("MinutesTypeExtraordinaryGeneralMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generalforsamling.
        /// </summary>
        public static string MinutesTypeGeneralMeeting {
            get {
                return ResourceManager.GetString("MinutesTypeGeneralMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværk.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværks ID.
        /// </summary>
        public static string NetworkID {
            get {
                return ResourceManager.GetString("NetworkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværksnavn.
        /// </summary>
        public static string NetworkName {
            get {
                return ResourceManager.GetString("NetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværk kan ikke vælges.
        /// </summary>
        public static string NetworkNotToShow {
            get {
                return ResourceManager.GetString("NetworkNotToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværks nr..
        /// </summary>
        public static string NetworkNumber {
            get {
                return ResourceManager.GetString("NetworkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny note.
        /// </summary>
        public static string NewNote {
            get {
                return ResourceManager.GetString("NewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyt kodeord.
        /// </summary>
        public static string Newpassword {
            get {
                return ResourceManager.GetString("Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det nye kodeord og bekræft kodeord er ikke ens.
        /// </summary>
        public static string NewPasswordsMustMatch {
            get {
                return ResourceManager.GetString("NewPasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyhedstype.
        /// </summary>
        public static string NewsType {
            get {
                return ResourceManager.GetString("NewsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyt kodeord og Komfimer nyt kodeor matcher ikke.
        /// </summary>
        public static string NoMatchPassword {
            get {
                return ResourceManager.GetString("NoMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note SMS sendt.
        /// </summary>
        public static string NoteSMSSendt {
            get {
                return ResourceManager.GetString("NoteSMSSendt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note SMS sent.
        /// </summary>
        public static string NoteTextSent {
            get {
                return ResourceManager.GetString("NoteTextSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer før for holdnote.
        /// </summary>
        public static string NoteTextTime {
            get {
                return ResourceManager.GetString("NoteTextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skal være mindst {2} tegn langt.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeord og bekræft kodeord er ikke ens.
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiltype.
        /// </summary>
        public static string PersonType {
            get {
                return ResourceManager.GetString("PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv (Går som Natteravn).
        /// </summary>
        public static string PersonTypeActive {
            get {
                return ResourceManager.GetString("PersonTypeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passiv (Går pt. ikke som Natteravn).
        /// </summary>
        public static string PersonTypePassiv {
            get {
                return ResourceManager.GetString("PersonTypePassiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter (Støtter Natteravnene).
        /// </summary>
        public static string PersonTypeSupport {
            get {
                return ResourceManager.GetString("PersonTypeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP (Vigtig person).
        /// </summary>
        public static string PersonTypeVIP {
            get {
                return ResourceManager.GetString("PersonTypeVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nr..
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postadresse.
        /// </summary>
        public static string Postaddress {
            get {
                return ResourceManager.GetString("Postaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilinformation.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato publisering.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huske SMS sendt.
        /// </summary>
        public static string ReminderTextSent {
            get {
                return ResourceManager.GetString("ReminderTextSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hver 2. uge.
        /// </summary>
        public static string RepetitionTypeBiWeekly {
            get {
                return ResourceManager.GetString("RepetitionTypeBiWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagligt.
        /// </summary>
        public static string RepetitionTypeDaily {
            get {
                return ResourceManager.GetString("RepetitionTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Månedligt.
        /// </summary>
        public static string RepetitionTypeMonthly {
            get {
                return ResourceManager.GetString("RepetitionTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen.
        /// </summary>
        public static string RepetitionTypeNone {
            get {
                return ResourceManager.GetString("RepetitionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hver 2. dag.
        /// </summary>
        public static string RepetitionTypeSecondday {
            get {
                return ResourceManager.GetString("RepetitionTypeSecondday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugentligt.
        /// </summary>
        public static string RepetitionTypeWeekly {
            get {
                return ResourceManager.GetString("RepetitionTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet &apos;{0}&apos; er obligatorisk.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet skal udfyldes!.
        /// </summary>
        public static string RequiredSingle {
            get {
                return ResourceManager.GetString("RequiredSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turliste tekst.
        /// </summary>
        public static string Scheduletext {
            get {
                return ResourceManager.GetString("Scheduletext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send note SMS.
        /// </summary>
        public static string SendNoteTeamleader {
            get {
                return ResourceManager.GetString("SendNoteTeamleader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send huske SMS.
        /// </summary>
        public static string SendTeamText {
            get {
                return ResourceManager.GetString("SendTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dage før for Hold SMS.
        /// </summary>
        public static string SendTeamTextDays {
            get {
                return ResourceManager.GetString("SendTeamTextDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaktør.
        /// </summary>
        public static string SetupEditor {
            get {
                return ResourceManager.GetString("SetupEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail nyhedsbreve.
        /// </summary>
        public static string SetupEmailNewsLetter {
            get {
                return ResourceManager.GetString("SetupEmailNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Førstehjælp.
        /// </summary>
        public static string SetupFoerstehjaelp {
            get {
                return ResourceManager.GetString("SetupFoerstehjaelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato førstehjælp.
        /// </summary>
        public static string SetupFoerstehjaelpDato {
            get {
                return ResourceManager.GetString("SetupFoerstehjaelpDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turplanlægger.
        /// </summary>
        public static string SetupPlanner {
            get {
                return ResourceManager.GetString("SetupPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NatteravneNyt.
        /// </summary>
        public static string SetupPrintNewslettet {
            get {
                return ResourceManager.GetString("SetupPrintNewslettet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekretær.
        /// </summary>
        public static string SetupSecretary {
            get {
                return ResourceManager.GetString("SetupSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Instruktør.
        /// </summary>
        public static string SetupSeniorInstructor {
            get {
                return ResourceManager.GetString("SetupSeniorInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Støttemedlem.
        /// </summary>
        public static string SetupStoettemedlem {
            get {
                return ResourceManager.GetString("SetupStoettemedlem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdleder.
        /// </summary>
        public static string SetupTeamleader {
            get {
                return ResourceManager.GetString("SetupTeamleader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kort navn.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis adresse.
        /// </summary>
        public static string ShowAddresse {
            get {
                return ResourceManager.GetString("ShowAddresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indmeldt.
        /// </summary>
        public static string SignupDate {
            get {
                return ResourceManager.GetString("SignupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttidspunkt.
        /// </summary>
        public static string Slut {
            get {
                return ResourceManager.GetString("Slut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Brugernavn skal udfyldes når &quot;Send Huske SMS&quot; er afkrydset.
        /// </summary>
        public static string SMSUserNameRequired {
            get {
                return ResourceManager.GetString("SMSUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilde.
        /// </summary>
        public static string SourceLevel {
            get {
                return ResourceManager.GetString("SourceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttidspunkt.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stjernetur.
        /// </summary>
        public static string StarTeam {
            get {
                return ResourceManager.GetString("StarTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet &apos;{0}&apos; skal være minimum {2} og maksimalt {1} karakterer langt.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdleder.
        /// </summary>
        public static string Teamleader {
            get {
                return ResourceManager.GetString("Teamleader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold log.
        /// </summary>
        public static string Teamlog {
            get {
                return ResourceManager.GetString("Teamlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ravn.
        /// </summary>
        public static string TeamMember {
            get {
                return ResourceManager.GetString("TeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ravne SMS.
        /// </summary>
        public static string TeamMessage {
            get {
                return ResourceManager.GetString("TeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdleder SMS.
        /// </summary>
        public static string TeamMessageTeamLeader {
            get {
                return ResourceManager.GetString("TeamMessageTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turtelefon.
        /// </summary>
        public static string TeamPhone {
            get {
                return ResourceManager.GetString("TeamPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. til evt. turtelefon.
        /// </summary>
        public static string TeamPhonePrompt {
            get {
                return ResourceManager.GetString("TeamPhonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aflyst.
        /// </summary>
        public static string TeamStatus_Cancelled {
            get {
                return ResourceManager.GetString("TeamStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedlagt.
        /// </summary>
        public static string TeamStatus_Droped {
            get {
                return ResourceManager.GetString("TeamStatus_Droped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TeamStatus_OK {
            get {
                return ResourceManager.GetString("TeamStatus_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlagt.
        /// </summary>
        public static string TeamStatus_Planned {
            get {
                return ResourceManager.GetString("TeamStatus_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaser.
        /// </summary>
        public static string Teaser {
            get {
                return ResourceManager.GetString("Teaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Kodeord.
        /// </summary>
        public static string TextServiceProviderPassword {
            get {
                return ResourceManager.GetString("TextServiceProviderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeord til www.cpsms.dk.
        /// </summary>
        public static string TextServiceProviderPasswordPrompt {
            get {
                return ResourceManager.GetString("TextServiceProviderPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Kodeord skal udfyldes når &quot;Send Huske SMS&quot; er afkrydset.
        /// </summary>
        public static string TextServiceProviderPasswordRequired {
            get {
                return ResourceManager.GetString("TextServiceProviderPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Brugernavn.
        /// </summary>
        public static string TextServiceProviderUserName {
            get {
                return ResourceManager.GetString("TextServiceProviderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavn til www.cpsms.dk.
        /// </summary>
        public static string TextServiceProviderUserNamePrompt {
            get {
                return ResourceManager.GetString("TextServiceProviderUserNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prøvetur.
        /// </summary>
        public static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prøvetur information.
        /// </summary>
        public static string TrialInfo {
            get {
                return ResourceManager.GetString("TrialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL (Webadresse).
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug regnskabs funktion.
        /// </summary>
        public static string UseAccounting {
            get {
                return ResourceManager.GetString("UseAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug kalender funktion.
        /// </summary>
        public static string UseCalender {
            get {
                return ResourceManager.GetString("UseCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug HotZones.
        /// </summary>
        public static string UseHotzones {
            get {
                return ResourceManager.GetString("UseHotzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug boks/lås kode funktion.
        /// </summary>
        public static string UseKeyBox {
            get {
                return ResourceManager.GetString("UseKeyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug Link Websiden.
        /// </summary>
        public static string UseLinksPage {
            get {
                return ResourceManager.GetString("UseLinksPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug liste funktion.
        /// </summary>
        public static string UseLists {
            get {
                return ResourceManager.GetString("UseLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug lokal nyhedsbrev funktion.
        /// </summary>
        public static string UseLocalNewsletter {
            get {
                return ResourceManager.GetString("UseLocalNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug lokation funktion.
        /// </summary>
        public static string UseLocation {
            get {
                return ResourceManager.GetString("UseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug LS nyhedsbrev funktion.
        /// </summary>
        public static string UseNationalNewsletter {
            get {
                return ResourceManager.GetString("UseNationalNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug Politi funktion.
        /// </summary>
        public static string UsePolicePlanning {
            get {
                return ResourceManager.GetString("UsePolicePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug Presse Websiden.
        /// </summary>
        public static string UsePressPage {
            get {
                return ResourceManager.GetString("UsePressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavn.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavnet &quot;{0}&quot; er ikke unik, vælg et nyt eller behold det eksisterende.
        /// </summary>
        public static string UserNameNotUnique {
            get {
                return ResourceManager.GetString("UserNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavnet &quot;{0}&quot; er ikke unik, brug det forslået eller vælg et nyt.
        /// </summary>
        public static string UserNameNotUniqueSuggestion {
            get {
                return ResourceManager.GetString("UserNameNotUniqueSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug Turplanlægning.
        /// </summary>
        public static string UseSchedulePlanning {
            get {
                return ResourceManager.GetString("UseSchedulePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug &quot;byt tur&quot; funktion.
        /// </summary>
        public static string UseShiftTeam {
            get {
                return ResourceManager.GetString("UseShiftTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug Sponsor Websiden.
        /// </summary>
        public static string UseSponsorPage {
            get {
                return ResourceManager.GetString("UseSponsorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug &quot;tag tur&quot; funktion.
        /// </summary>
        public static string UseTakeTeamSpot {
            get {
                return ResourceManager.GetString("UseTakeTeamSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brug Turbørs.
        /// </summary>
        public static string UseTeamExchange {
            get {
                return ResourceManager.GetString("UseTeamExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visninger.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki indhold.
        /// </summary>
        public static string WikiBody {
            get {
                return ResourceManager.GetString("WikiBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emne titel.
        /// </summary>
        public static string WikiTitle {
            get {
                return ResourceManager.GetString("WikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ord.
        /// </summary>
        public static string WikiWord {
            get {
                return ResourceManager.GetString("WikiWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet &apos;{0}&apos; indeholder ikke et korrekte e-mail format.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet &apos;{0}&apos; indeholder ikke et korrekte URL format.
        /// </summary>
        public static string WrongURLFormat {
            get {
                return ResourceManager.GetString("WrongURLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post nr.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
