//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR.Localication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Local_Homepage.Localisation.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-user-times.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-ban-circle.
        /// </summary>
        public static string AbsentIcon {
            get {
                return ResourceManager.GetString("AbsentIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-ticket.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-money.
        /// </summary>
        public static string Accountant {
            get {
                return ResourceManager.GetString("Accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-money.
        /// </summary>
        public static string AccountantAlternate {
            get {
                return ResourceManager.GetString("AccountantAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-user.
        /// </summary>
        public static string AdminIcon {
            get {
                return ResourceManager.GetString("AdminIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string AdminTxt {
            get {
                return ResourceManager.GetString("AdminTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-pause.
        /// </summary>
        public static string Alternate {
            get {
                return ResourceManager.GetString("Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-money.
        /// </summary>
        public static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-pause.
        /// </summary>
        public static string AuditorAlternate {
            get {
                return ResourceManager.GetString("AuditorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-reply.
        /// </summary>
        public static string BackIcon {
            get {
                return ResourceManager.GetString("BackIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-archive.
        /// </summary>
        public static string BasicInfoIcon {
            get {
                return ResourceManager.GetString("BasicInfoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-heart-empty.
        /// </summary>
        public static string BasicTraining {
            get {
                return ResourceManager.GetString("BasicTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-users.
        /// </summary>
        public static string BoardMember {
            get {
                return ResourceManager.GetString("BoardMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-anchor.
        /// </summary>
        public static string Chairman {
            get {
                return ResourceManager.GetString("Chairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-trash-o.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-pencil.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-pencil.
        /// </summary>
        public static string EditIcon {
            get {
                return ResourceManager.GetString("EditIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-keyboard-o.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger.
        /// </summary>
        public static string EditTxt {
            get {
                return ResourceManager.GetString("EditTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-send.
        /// </summary>
        public static string EmailNewsLetter {
            get {
                return ResourceManager.GetString("EmailNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-retweet.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-list-alt.
        /// </summary>
        public static string FolderList {
            get {
                return ResourceManager.GetString("FolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-table.
        /// </summary>
        public static string FolderPlanning {
            get {
                return ResourceManager.GetString("FolderPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-time.
        /// </summary>
        public static string LastchangedIcon {
            get {
                return ResourceManager.GetString("LastchangedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-map-marker.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-key.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-key.
        /// </summary>
        public static string LoginInfoIcon {
            get {
                return ResourceManager.GetString("LoginInfoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log ind detaljer.
        /// </summary>
        public static string LoginInfoTxt {
            get {
                return ResourceManager.GetString("LoginInfoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-comment.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-adn.
        /// </summary>
        public static string NotificationTypeAssociation {
            get {
                return ResourceManager.GetString("NotificationTypeAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-comment.
        /// </summary>
        public static string NotificationTypeAssociationNote {
            get {
                return ResourceManager.GetString("NotificationTypeAssociationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-file-text-o.
        /// </summary>
        public static string NotificationTypeContent {
            get {
                return ResourceManager.GetString("NotificationTypeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-bookmark.
        /// </summary>
        public static string NotificationTypeEvent {
            get {
                return ResourceManager.GetString("NotificationTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-folder.
        /// </summary>
        public static string NotificationTypeFolder {
            get {
                return ResourceManager.GetString("NotificationTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-info-circle.
        /// </summary>
        public static string NotificationTypeNewVersion {
            get {
                return ResourceManager.GetString("NotificationTypeNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-user.
        /// </summary>
        public static string NotificationTypePerson {
            get {
                return ResourceManager.GetString("NotificationTypePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-users.
        /// </summary>
        public static string NotificationTypeTeam {
            get {
                return ResourceManager.GetString("NotificationTypeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-envelope.
        /// </summary>
        public static string NotificationTypeUnknown {
            get {
                return ResourceManager.GetString("NotificationTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-book.
        /// </summary>
        public static string NotificationTypeWiki {
            get {
                return ResourceManager.GetString("NotificationTypeWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-calendar.
        /// </summary>
        public static string Planner {
            get {
                return ResourceManager.GetString("Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turplanlægger.
        /// </summary>
        public static string PlannerTxt {
            get {
                return ResourceManager.GetString("PlannerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-thumbs-o-down icon-only bigger-150 light-grey.
        /// </summary>
        public static string PlanningAnswerFalse {
            get {
                return ResourceManager.GetString("PlanningAnswerFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-question-circle icon-only light-grey.
        /// </summary>
        public static string PlanningAnswerNull {
            get {
                return ResourceManager.GetString("PlanningAnswerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-group icon-only green.
        /// </summary>
        public static string PlanningAnswerTeamleader {
            get {
                return ResourceManager.GetString("PlanningAnswerTeamleader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-male icon-only green.
        /// </summary>
        public static string PlanningAnswerTeammember {
            get {
                return ResourceManager.GetString("PlanningAnswerTeammember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-male icon-only bigger-150 light-grey.
        /// </summary>
        public static string PlanningAnswerTrue {
            get {
                return ResourceManager.GetString("PlanningAnswerTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-envelope.
        /// </summary>
        public static string PrintNewslettet {
            get {
                return ResourceManager.GetString("PrintNewslettet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-zoom-in.
        /// </summary>
        public static string ProfilIcon {
            get {
                return ResourceManager.GetString("ProfilIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-camera.
        /// </summary>
        public static string ProfilImage {
            get {
                return ResourceManager.GetString("ProfilImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-pencil-square-o.
        /// </summary>
        public static string Secretary {
            get {
                return ResourceManager.GetString("Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-life-ring.
        /// </summary>
        public static string SeniorInstructorIcon {
            get {
                return ResourceManager.GetString("SeniorInstructorIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-users.
        /// </summary>
        public static string SteeringGroupMemberIcon {
            get {
                return ResourceManager.GetString("SteeringGroupMemberIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-compass.
        /// </summary>
        public static string TeamLeader {
            get {
                return ResourceManager.GetString("TeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-ban-circle.
        /// </summary>
        public static string TeamleaderIcon {
            get {
                return ResourceManager.GetString("TeamleaderIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-graduation-cap.
        /// </summary>
        public static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-certificate.
        /// </summary>
        public static string ViceChairmanIcon {
            get {
                return ResourceManager.GetString("ViceChairmanIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næstformand.
        /// </summary>
        public static string ViceChairmanTxt {
            get {
                return ResourceManager.GetString("ViceChairmanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-eye.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
